modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/187J3X1-114514/superresolution/issues"
license = "MIT"

[[mods]]
modId = "super_resolution"
version = "0.8.3-alpha.6+opengl"
displayName = "Super Resolution"
authors = "187J3X1"
description = '''
喵
'''
logoFile = "assets/super_resolution/textures/gui/logo.png"

[[dependencies.super_resolution]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[mods."sodium:options"]
"mixin.features.render.gui.debug" = false
"mixin.workarounds" = false

[modproperties.super_resolution]
"sodium:config_api_user" = "io.homo.superresolution.fabric.compat.sodium.SodiumConfigBuilder"

[[mixins]]
config = "super_resolution.mixins.json"
[[mixins]]
config = "super_resolution.hack.mixins.json"
[[mixins]]
config = "super_resolution-neoforge.mixins.json"
[[mixins]]
config = "super_resolution-neoforge-compat.mixins.json"
[[mixins]]
config = "super_resolution_irisapi.mixins.json"
[[mixins]]
config = "super_resolution.shadercompat.mixins.json"
